CREATE TABLE SITUACAO(
    ID_SITUACAO INTEGER,
    SITUACAO VARCHAR(10),
    CONSTRAINT PK_SITUACAO PRIMARY KEY (ID_SITUACAO)
);

CREATE TABLE SOCIO (
    ID_SOCIO INTEGER,
    NOME VARCHAR(256),
    CPF VARCHAR(11),
    EMAIL VARCHAR(256),
    ID_SITUACAO INTEGER,
    CONSTRAINT PK_SOCIO PRIMARY KEY (ID_SOCIO),
    CONSTRAINT FK_SOCIO_REF_SITUACAO FOREIGN KEY (ID_SITUACAO)
        REFERENCES SITUACAO (ID_SITUACAO)
);

CREATE TABLE MARCA(
    ID_MARCA INTEGER,
    MARCA VARCHAR(128),
    CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA)
);

CREATE TABLE CARRO (
    ID_CARRO INTEGER,
    MODELO VARCHAR(128),
    COR VARCHAR(64),
    PLACA VARCHAR(10),
    ID_SOCIO INTEGER,
    ID_MARCA INTEGER,
    CONSTRAINT PK_CARRO PRIMARY KEY (ID_CARRO),
    CONSTRAINT FK_CARRO_REF_SOCIO FOREIGN KEY (ID_SOCIO)
        REFERENCES SOCIO (ID_SOCIO),
    CONSTRAINT FK_CARRO_REF_MARCA FOREIGN KEY (ID_MARCA)
        REFERENCES MARCA (ID_MARCA)
);